# In general, when you are trying to build from a public
# repository, no secrets are needed.
# When using a private repository, you'll need to provide credentials.
# See config.authFlow for details on what flow to choose.

# Depending on the chosen auth flow, you need either
# `passwordFlowOptions` or `patFlowOptions`.
# The unused one can be commented out.

# When using authFlow="PasswordFlow"
passwordFlowOptions:
    username: your-username
    password: your-password

# when using authFlow="PATFlow"
patFlowOptions:
    username: your-username
    token: your-personal-access-token
