# What port your neuron site is exposed at
port: 8080

# Simple credentials for http basic auth
users:
  - username: my-username
    password: my-password
  - username: second-user
    password: super-secure